myproject/myapp/urls.py
from django.urls import path

from .views import MyModelView, ElectronicView, WearView

app_name= 'myapp'

urlpatterns = [
    path('', MyModelView.as_view(), name='index'),
    path('electronic/', ElectronicView.as_view(), name='electronic'),
    path('wear/', WearView.as_view(), name='wear')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myproject/myapp/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager

# Create your models here.
class MyAppModel(models.Model):
    name = models.CharField(max_length=64, default='Unknown')
    recieve_date = models.DateField(auto_now_add=True)
    price = models.IntegerField(default=0)
    unit = models.CharField(max_length=15)
    producer = models.CharField(max_length=64)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    objects = CurrentSiteManager('site')

    def __str__(self):
        return self.name


class CategoriesModel(models.Model):
    category = models.CharField(max_length=64, default='Unknown')
    product = models.ManyToManyField(MyAppModel, related_name='product')
    objects = models.Manager()

    def __str__(self):
        return self.category

myproject/myapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from .models import MyAppModel, CategoriesModel

class MyModelView(ListView):
    model = CategoriesModel
    template_name = 'index.html'
    queryset = CategoriesModel.objects.all()

class ElectronicView(ListView):
    model = CategoriesModel
    template_name = 'electronic.html'
    queryset = CategoriesModel.objects.prefetch_related('product').all()

class WearView(ListView):
    model = CategoriesModel
    template_name = 'wear.html'
    queryset = CategoriesModel.objects.prefetch_related('product').all()

myproject/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

myproject/templates/electronic.html
{% extends 'base.html' %}
{% block content %}
<table>
    <tr>
        <th>
            name
        </th>
        <th>
            recieve_date
        </th>
        <th>
            price
        </th>
        <th>
            unit
        </th>
        <th>
            producer
        </th>
    </tr>
{% for object in object_list %}
    {{object}}
    {% if object.category == 'electronic' %}
        <tr>
            <td>{{ object.product.site }}</td>
            <td>{{ object.product.name }}</td>
            <td>{{ object.product.recieve_date }}</td>
            <td>{{ object.product.price }}</td>
            <td>{{ object.product.unit }}</td>
            <td>{{ object.product.producer }}</td>
        </tr>
    {% endif %}
{% endfor %}
</table>
{% endblock %}

myproject/templates/index.html
{% extends 'base.html' %}
{% block content %}
<table>
    <tr>
        <th>
            category
        </th>

    </tr>

    <tr>
        <td>
            <a href="{% url 'myapp:electronic' %}">Электроника</a>
        </td>
         <td>
            <a href="{% url 'myapp:wear' %}">Одежда</a>
        </td>

</table>
{% endblock %}

myproject/templates/wear.html
{% extends 'base.html' %}
{% block content %}
<table>
    <tr>
        <th>
            name
        </th>
        <th>
            recieve_date
        </th>
        <th>
            price
        </th>
        <th>
            unit
        </th>
        <th>
            producer
        </th>
    </tr>
{% for object in object_list %}
    {% if object.category == 'wear' %}
        <tr>
            <td>{{ object.product.site }}</td>
            <td>{{ object.product.name }}</td>
            <td>{{ object.product.recieve_date }}</td>
            <td>{{ object.product.price }}</td>
            <td>{{ object.product.unit }}</td>
            <td>{{ object.product.producer }}</td>
        </tr>
    {% endif %}
{% endfor %}
</table>
{% endblock %}